name: PeriMyo Tutorial

datasets:
  perimyo_data:
    path: data/perimyo_combined.csv


views:
  perimyo_data:
    dataset: perimyo_data
    desc: |
      Synthetic PeriMyo data set
    render-table:
      columns:
        regex('lab_*'):
          plot:
            heatmap:
              scale: linear
              range: ["white", "blue"]
        # regex('ICD_*|OPS_*'):
        regex('OPS_*'):
          plot:
            heatmap:
              type: nominal
        regex('ICD_*|TROP|gender_female'):
          spell:
            url: v1.3.0/logic/boolean
            with:
              # specify which values should be interpreted as true or false
              true_value: "True"
              false_value: "False"
        age_at_OP:
          plot:
            ticks:
              scale: linear
              color:
                range:
                  - "#fee8c8"
                  - "#e34a33"
        condition_main:
          # link-to-url:
          #   ICD-10:
          #     url: https://gesund.bund.de/en/icd-code-search/{value}
          #     new-window: true
          custom-plot:
            data: |
              function (value, row) {
                return [
                  {
                    "category": value.charAt(0)
                  }
                ]
              }
            spec: |
              {
                "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
                "height": 25,
                "width": 25,
                "mark": {"type": "rect", "tooltip": true},
                "encoding": {
                  "y": {"field": "category", "type": "nominal"},
                  "color": {
                    "field": "category",
                    "type": "nominal",
                    "scale": {"scheme": "category20"}
                  }
                },
                "config": {
                  "legend": {"disable": true}
                }
              }
      add-columns:
        condition_main_processed:
          value: |
            function (row) {
              return row['condition_main'].charAt(0)
            }




